package cr.ac.una.prograiv.taxi.domain;
// Generated 18-oct-2017 14:51:36 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable, Jsonable{


     private String usuarioIdUsuario;
     private Usuario usuario;
     private Vehiculo vehiculo;
     private String tipoLicencia;
     private Date licenciaVence;
     private int puntuacion;
     private int cedula;

    public Conductor() {
    }
    
    public boolean equals(Conductor c){
        return this.usuarioIdUsuario.equals(c.getUsuarioIdUsuario());
    }
    
    public boolean equals(Usuario u){
        return this.usuario.equals(u);
    }
	
    public Conductor(Usuario usuario, Vehiculo vehiculo, String tipoLicencia, Date licenciaVence, int puntuacion, int cedula) {
        this.usuario = usuario;
        this.vehiculo = vehiculo;
        this.tipoLicencia = tipoLicencia;
        this.licenciaVence = licenciaVence;
        this.puntuacion = puntuacion;
        this.cedula = cedula;
    }
   
    public String getUsuarioIdUsuario() {
        return this.usuarioIdUsuario;
    }
    
    public void setUsuarioIdUsuario(String usuarioIdUsuario) {
        this.usuarioIdUsuario = usuarioIdUsuario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getTipoLicencia() {
        return this.tipoLicencia;
    }
    
    public void setTipoLicencia(String tipoLicencia) {
        this.tipoLicencia = tipoLicencia;
    }
    public Date getLicenciaVence() {
        return this.licenciaVence;
    }
    
    public void setLicenciaVence(Date licenciaVence) {
        this.licenciaVence = licenciaVence;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }

    public String toString(){
          return 
                   "\n{usuarioIdUsuario: "+ this.usuarioIdUsuario
                  +", usuario: "+this.usuario
                  +", vehiculo: "+this.vehiculo
                  +", tipoLicencia: "+this.tipoLicencia
                  +", licenciaVence: "+this.licenciaVence
                  +", puntuacion: "+this.puntuacion
                  +", cedula: "+this.cedula
                  +"}\n";
    }


}


