package cr.ac.una.prograiv.taxi.domain;
// Generated 23-oct-2017 21:29:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable, Jsonable{


     private Integer id;
     private double lat;
     private double lng;
     private String nombre;
     private Integer zoom;

    public Direccion() {
    }

	
    public Direccion(double lat, double lng) {
        this.lat = lat;
        this.lng = lng;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public double getLat() {
        return this.lat;
    }
    
    public void setLat(double lat) {
        this.lat = lat;
    }
    public double getLng() {
        return this.lng;
    }
    
    public void setLng(double lng) {
        this.lng = lng;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getZoom() {
        return this.zoom;
    }
    
    public void setZoom(Integer zoom) {
        this.zoom = zoom;
    }

}


