package cr.ac.una.prograiv.taxi.domain;
// Generated 06-oct-2017 16:09:42 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable, Jsonable {


     private String idUsuario;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private Date fechaNacimiento;
     private int telefono;
     private String correo;
     private String password;
     private boolean esAdministrador;
     private String direccion;
     private Conductor conductor;
     private List<Viaje> viajes = new ArrayList();

    public Usuario() {
    }

	
    public Usuario(String idUsuario, String nombre, String apellido1, String apellido2, Date fechaNacimiento, int telefono, String correo, String password, boolean esAdministrador, String direccion) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.fechaNacimiento = fechaNacimiento;
        this.telefono = telefono;
        this.correo = correo;
        this.password = password;
        this.esAdministrador = esAdministrador;
        this.direccion = direccion;
    }
    public Usuario(String idUsuario, String nombre, String apellido1, String apellido2, Date fechaNacimiento, int telefono, String correo, String password, boolean esAdministrador, String direccion, Conductor conductor, List<Viaje> viajes) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.fechaNacimiento = fechaNacimiento;
       this.telefono = telefono;
       this.correo = correo;
       this.password = password;
       this.esAdministrador = esAdministrador;
       this.direccion = direccion;
       this.conductor = conductor;
       this.viajes = viajes;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEsAdministrador() {
        return this.esAdministrador;
    }
    
    public void setEsAdministrador(boolean esAdministrador) {
        this.esAdministrador = esAdministrador;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public List<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(List<Viaje> viajes) {
        this.viajes = viajes;
    }

    public String toString(){
            return 
                    "\n{idUsuario: "+this.idUsuario
                    +", nombre: "+this.nombre +" "+ this.apellido1 +" "+this.apellido2
                    +", fecha de nacimiento: "+this.fechaNacimiento
                    +", telefono: "+this.telefono
                    +", correo: "+this.correo
                    +", password: "+this.password
                    +", es administrador: "+((this.esAdministrador)?"si":"no")
                    +", direccion: "+this.direccion
                    +"}\n";
    }


}


