package cr.ac.una.prograiv.taxi.domain;
// Generated 23-oct-2017 21:29:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable, Jsonable{


     private String idUsuario;
     private Direccion direccion;
     private String nombre;
     private String apellidos;
     private Date fechaNacimiento;
     private int telefono;
     private String correo;
     private String password;
     private boolean esAdministrador;
     private Conductor conductor;

    public Usuario() {
    }
    
    public boolean equals(Usuario u){
        return this.idUsuario.equals(u.getIdUsuario());
    }

	
    public Usuario(String idUsuario, Direccion direccion, String nombre, String apellidos, Date fechaNacimiento, int telefono, String correo, String password, boolean esAdministrador) {
        this.idUsuario = idUsuario;
        this.direccion = direccion;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechaNacimiento = fechaNacimiento;
        this.telefono = telefono;
        this.correo = correo;
        this.password = password;
        this.esAdministrador = esAdministrador;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEsAdministrador() {
        return this.esAdministrador;
    }
    
    public void setEsAdministrador(boolean esAdministrador) {
        this.esAdministrador = esAdministrador;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }

      public String toString() {
        return "\n{idUsuario: " + this.idUsuario
                + ", nombre: " + this.nombre + " " + this.apellidos
                + ", fecha de nacimiento: " + this.fechaNacimiento
                + ", telefono: " + this.telefono
                + ", correo: " + this.correo
                + ", password: " + this.password
                + ", es administrador: " + ((this.esAdministrador) ? "si" : "no")
                + ", direccion: " + this.direccion
                + "}\n";
    }

}


