package cr.ac.una.prograiv.taxi.domain;
// Generated 22-oct-2017 21:54:06 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo implements java.io.Serializable, Jsonable {

    private String placa;
    private int ano;
    private String modelo;
    private String marca;
    private String color;
    private boolean estado;

    public Vehiculo() {
    }

    public Vehiculo(String placa, int ano, String modelo, String marca, String color, boolean estado) {
        this.placa = placa;
        this.ano = ano;
        this.modelo = modelo;
        this.marca = marca;
        this.color = color;
        this.estado = estado;
    }

    public String getPlaca() {
        return this.placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public int getAno() {
        return this.ano;
    }

    public void setAno(int ano) {
        this.ano = ano;
    }

    public String getModelo() {
        return this.modelo;
    }

    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    public String getMarca() {
        return this.marca;
    }

    public void setMarca(String marca) {
        this.marca = marca;
    }

    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public String toString() {
        return "\n{placa: " + this.placa
                + ", modelo: " + this.modelo
                + ", año: " + this.ano
                + ", marca: "+ this.marca
                + ", color: " + this.color
                + ", estado" + ((this.estado) ? "activo" : "inactivo")
                + "}\n";
    }

}
