package cr.ac.una.prograiv.taxi.domain;
// Generated 23-oct-2017 21:29:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable, Jsonable {


     private Integer idViaje;
     private Direccion direccionByDireccionIdDestino;
     private Direccion direccionByDireccionIdOrigen;
     private Usuario usuarioByConductor;
     private Usuario usuarioByUsuario;
     private Date fecha;
     private String duracion;
     private int monto;
     private int puntaje;
     private String comentario;

    public Viaje() {
    }

	
    public Viaje(Direccion direccionByDireccionIdDestino, Direccion direccionByDireccionIdOrigen, Usuario usuarioByConductor, Usuario usuarioByUsuario, Date fecha, String duracion, int monto, int puntaje) {
        this.direccionByDireccionIdDestino = direccionByDireccionIdDestino;
        this.direccionByDireccionIdOrigen = direccionByDireccionIdOrigen;
        this.usuarioByConductor = usuarioByConductor;
        this.usuarioByUsuario = usuarioByUsuario;
        this.fecha = fecha;
        this.duracion = duracion;
        this.monto = monto;
        this.puntaje = puntaje;
    }
    public Viaje(Direccion direccionByDireccionIdDestino, Direccion direccionByDireccionIdOrigen, Usuario usuarioByConductor, Usuario usuarioByUsuario, Date fecha, String duracion, int monto, int puntaje, String comentario) {
       this.direccionByDireccionIdDestino = direccionByDireccionIdDestino;
       this.direccionByDireccionIdOrigen = direccionByDireccionIdOrigen;
       this.usuarioByConductor = usuarioByConductor;
       this.usuarioByUsuario = usuarioByUsuario;
       this.fecha = fecha;
       this.duracion = duracion;
       this.monto = monto;
       this.puntaje = puntaje;
       this.comentario = comentario;
    }
   
    public Integer getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(Integer idViaje) {
        this.idViaje = idViaje;
    }
    public Direccion getDireccionByDireccionIdDestino() {
        return this.direccionByDireccionIdDestino;
    }
    
    public void setDireccionByDireccionIdDestino(Direccion direccionByDireccionIdDestino) {
        this.direccionByDireccionIdDestino = direccionByDireccionIdDestino;
    }
    public Direccion getDireccionByDireccionIdOrigen() {
        return this.direccionByDireccionIdOrigen;
    }
    
    public void setDireccionByDireccionIdOrigen(Direccion direccionByDireccionIdOrigen) {
        this.direccionByDireccionIdOrigen = direccionByDireccionIdOrigen;
    }
    public Usuario getUsuarioByConductor() {
        return this.usuarioByConductor;
    }
    
    public void setUsuarioByConductor(Usuario usuarioByConductor) {
        this.usuarioByConductor = usuarioByConductor;
    }
    public Usuario getUsuarioByUsuario() {
        return this.usuarioByUsuario;
    }
    
    public void setUsuarioByUsuario(Usuario usuarioByUsuario) {
        this.usuarioByUsuario = usuarioByUsuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


