package cr.ac.una.prograiv.taxi.domain;
// Generated 21-oct-2017 19:50:53 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable, Jsonable {


     private int idViaje;
     private Usuario usuarioByConductor;
     private Usuario usuarioByUsuario;
     private Date fecha;
     private String duracion;
     private int monto;
     private Serializable direccionNombreOrigen;
     private Serializable direccionNombreDestino;
     private int puntaje;
     private String comentario;

    public Viaje() {
    }

	
    public Viaje(int idViaje, Usuario usuarioByConductor, Usuario usuarioByUsuario, Date fecha, String duracion, int monto, Serializable direccionNombreOrigen, Serializable direccionNombreDestino, int puntaje) {
        this.idViaje = idViaje;
        this.usuarioByConductor = usuarioByConductor;
        this.usuarioByUsuario = usuarioByUsuario;
        this.fecha = fecha;
        this.duracion = duracion;
        this.monto = monto;
        this.direccionNombreOrigen = direccionNombreOrigen;
        this.direccionNombreDestino = direccionNombreDestino;
        this.puntaje = puntaje;
    }
    public Viaje(int idViaje, Usuario usuarioByConductor, Usuario usuarioByUsuario, Date fecha, String duracion, int monto, Serializable direccionNombreOrigen, Serializable direccionNombreDestino, int puntaje, String comentario) {
       this.idViaje = idViaje;
       this.usuarioByConductor = usuarioByConductor;
       this.usuarioByUsuario = usuarioByUsuario;
       this.fecha = fecha;
       this.duracion = duracion;
       this.monto = monto;
       this.direccionNombreOrigen = direccionNombreOrigen;
       this.direccionNombreDestino = direccionNombreDestino;
       this.puntaje = puntaje;
       this.comentario = comentario;
    }
   
    public int getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(int idViaje) {
        this.idViaje = idViaje;
    }
    public Usuario getUsuarioByConductor() {
        return this.usuarioByConductor;
    }
    
    public void setUsuarioByConductor(Usuario usuarioByConductor) {
        this.usuarioByConductor = usuarioByConductor;
    }
    public Usuario getUsuarioByUsuario() {
        return this.usuarioByUsuario;
    }
    
    public void setUsuarioByUsuario(Usuario usuarioByUsuario) {
        this.usuarioByUsuario = usuarioByUsuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public Serializable getDireccionNombreOrigen() {
        return this.direccionNombreOrigen;
    }
    
    public void setDireccionNombreOrigen(Serializable direccionNombreOrigen) {
        this.direccionNombreOrigen = direccionNombreOrigen;
    }
    public Serializable getDireccionNombreDestino() {
        return this.direccionNombreDestino;
    }
    
    public void setDireccionNombreDestino(Serializable direccionNombreDestino) {
        this.direccionNombreDestino = direccionNombreDestino;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


