package cr.ac.una.prograiv.taxi.domain;
// Generated 22-oct-2017 21:54:06 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable, Jsonable {


     private int idViaje;
     private Direccion direccionByDireccionDestino;
     private Direccion direccionByDireccionOrigen;
     private Usuario usuarioByConductor;
     private Usuario usuarioByUsuario;
     private Date fecha;
     private String duracion;
     private int monto;
     private int puntaje;
     private String comentario;

    public Viaje() {
    }

	
    public Viaje(int idViaje, Direccion direccionByDireccionDestino, Direccion direccionByDireccionOrigen, Usuario usuarioByConductor, Usuario usuarioByUsuario, Date fecha, String duracion, int monto, int puntaje) {
        this.idViaje = idViaje;
        this.direccionByDireccionDestino = direccionByDireccionDestino;
        this.direccionByDireccionOrigen = direccionByDireccionOrigen;
        this.usuarioByConductor = usuarioByConductor;
        this.usuarioByUsuario = usuarioByUsuario;
        this.fecha = fecha;
        this.duracion = duracion;
        this.monto = monto;
        this.puntaje = puntaje;
    }
    public Viaje(int idViaje, Direccion direccionByDireccionDestino, Direccion direccionByDireccionOrigen, Usuario usuarioByConductor, Usuario usuarioByUsuario, Date fecha, String duracion, int monto, int puntaje, String comentario) {
       this.idViaje = idViaje;
       this.direccionByDireccionDestino = direccionByDireccionDestino;
       this.direccionByDireccionOrigen = direccionByDireccionOrigen;
       this.usuarioByConductor = usuarioByConductor;
       this.usuarioByUsuario = usuarioByUsuario;
       this.fecha = fecha;
       this.duracion = duracion;
       this.monto = monto;
       this.puntaje = puntaje;
       this.comentario = comentario;
    }
   
    public int getIdViaje() {
        return this.idViaje;
    }
    
    public void setIdViaje(int idViaje) {
        this.idViaje = idViaje;
    }
    public Direccion getDireccionByDireccionDestino() {
        return this.direccionByDireccionDestino;
    }
    
    public void setDireccionByDireccionDestino(Direccion direccionByDireccionDestino) {
        this.direccionByDireccionDestino = direccionByDireccionDestino;
    }
    public Direccion getDireccionByDireccionOrigen() {
        return this.direccionByDireccionOrigen;
    }
    
    public void setDireccionByDireccionOrigen(Direccion direccionByDireccionOrigen) {
        this.direccionByDireccionOrigen = direccionByDireccionOrigen;
    }
    public Usuario getUsuarioByConductor() {
        return this.usuarioByConductor;
    }
    
    public void setUsuarioByConductor(Usuario usuarioByConductor) {
        this.usuarioByConductor = usuarioByConductor;
    }
    public Usuario getUsuarioByUsuario() {
        return this.usuarioByUsuario;
    }
    
    public void setUsuarioByUsuario(Usuario usuarioByUsuario) {
        this.usuarioByUsuario = usuarioByUsuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public int getMonto() {
        return this.monto;
    }
    
    public void setMonto(int monto) {
        this.monto = monto;
    }
    public int getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(int puntaje) {
        this.puntaje = puntaje;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


